### ISSUE TITLE
Call to undefined method SpecialConnect::getPageTitle

### ISSUE THREAD

**Issue by proteusbr** [garbear/facebook-mediawiki#8]
My site wikidaviagem.com

I my LocalSettings.php I put:
# Facebook

require_once ( "$IP/extensions/Facebook/Facebook.php" );
$wgFbAppId  = '432689303500279';
$wgFbSecret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'; (replace for X)
$wgFbNamespace      = 'loginwikidaviagem';
$wgFbAllowDebug = true;
$wgFbOpenGraph = true;

Run the update.php
Make the app in facebook

What I Get when I try login

[82463615] /index.php?title=Special:Connect Exception from line 376 of /opt/bitnami/apps/mediawiki/htdocs/includes/SpecialPage.php: Call to undefined method SpecialConnect::getPageTitle
Backtrace:
#0 /opt/bitnami/apps/mediawiki/htdocs/extensions/Facebook/SpecialConnect.php(1028): SpecialPage->__call(string, array)
#1 /opt/bitnami/apps/mediawiki/htdocs/extensions/Facebook/SpecialConnect.php(1028): SpecialConnect->getPageTitle(string)
#2 /opt/bitnami/apps/mediawiki/htdocs/extensions/Facebook/SpecialConnect.php(1006): SpecialConnect->getChooseNameForm(NULL, string, string)
#3 /opt/bitnami/apps/mediawiki/htdocs/extensions/Facebook/SpecialConnect.php(116): SpecialConnect->connectNewUserView()
#4 /opt/bitnami/apps/mediawiki/htdocs/extensions/Facebook/SpecialConnect.php(405): SpecialConnect->sendPage(string)
#5 /opt/bitnami/apps/mediawiki/htdocs/includes/SpecialPage.php(631): SpecialConnect->execute(NULL)
#6 /opt/bitnami/apps/mediawiki/htdocs/includes/SpecialPageFactory.php(488): SpecialPage->run(NULL)
#7 /opt/bitnami/apps/mediawiki/htdocs/includes/Wiki.php(298): SpecialPageFactory::executePath(Title, RequestContext)
#8 /opt/bitnami/apps/mediawiki/htdocs/includes/Wiki.php(602): MediaWiki->performRequest()
#9 /opt/bitnami/apps/mediawiki/htdocs/includes/Wiki.php(467): MediaWiki->main()
#10 /opt/bitnami/apps/mediawiki/htdocs/index.php(49): MediaWiki->run()
#11 {main}

**Comment by garbear** [comment]
SpecialPage::getPageTitle() has probably been removed in your version of MediaWiki. What version are you running?

**Comment by proteusbr** [comment]
ProdutoVersão
MediaWiki1.22.1
PHP5.4.24 (fpm-fcgi)
MySQL5.5.34

**Comment by engeneeringhall** [comment]
you solve this problem??
